### PR TITLE
Feat: Add a new Data item

### PR DESCRIPTION
**Pull request by SushanShakya**
## ✔️ Check List (Check all the applicable boxes) 

- [ X ] My code follows the code style of this project.
- [ X ] This PR does not contain plagiarized content.
- [ X ] The title of my pull request is a short description of the requested changes.
- [ X ] I am a participant of Hacktoberfest 2022.

### CODE REVIEW

**Comment by rezwancs** [comment]
Please add at least 4 flashcards about "ReactJS" concepts in a single PR.

**Comment by SushanShakya** [comment]
Adds 3 more flashcards making a total of 4 flashcards
@rezwan2525

**Comment by SushanShakya** [comment]
@rezwan2525 
Please Reply.

**Comment by rezwancs** [comment]
@SushanShakya  Amazing. Thanks for contributing. 🤩 Please don't forget to star the repository

**Pull request merged**
