### PR TITLE
dark mode added

### PR DESCRIPTION
**Pull request by prerit2001**
## 👨‍💻 Changes proposed: 

Added Dark Mode

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.
- [x] I am a participant of Hacktoberfest 2022.

## 📷 Screenshots
image
light mode

image
dark mode

### CODE REVIEW

**Comment by rezwancs** [comment]
@prerit2001 Could you please sync with the "main" branch and resolve the merge conflict?

**Comment by prerit2001** [comment]
> @prerit2001 Could you please sync with the "main" branch and resolve the merge conflict?

Resolved the conflict. Please merge and label issue with hacktoberfest-accepted.

**Comment by rezwancs** [comment]
@prerit2001 Could you please check the review feedback ?

**Comment by prerit2001** [comment]
didn't get it? Can you elaborate a little?

**Comment by rezwancs** [comment]
@prerit2001 We have provided you some feedback comments on your codes. Could you please check those ?

**Pull request closed without merging**
